- name: Clone frontman
  remote_user: ubuntu
  git:
    repo: https://github.com/Dunklas/frontman
    dest: /tmp/frontman
    clone: yes
    update: yes
- name: Copy servers.json
  remote_user: ubuntu
  copy:
    src: ../servers.json
    dest: /tmp/frontman
    owner: ubuntu
    mode: u=r,g=r,o=r
- name: Start frontman
  remote_user: ubuntu
  make:
    chdir: /tmp/frontman
    target: start
