name: Deploy server
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: iac
    outputs:
      ip: ${{ steps.obtain_ip.outputs.ip }}
    steps:
      - uses: actions/checkout@v2
      - name: terraform init
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}"
        env:
          TF_STATE_BUCKET: appserver-tfstate
          TF_STATE_KEY: appserver.tfstate
      - name: terraform plan
        run: |
          terraform plan \
            -var="hosted_zone_id=${{ env.HOSTED_ZONE_ID }}" \
            -var='sub_domains=${{ env.SUB_DOMAINS }}' \
            -out=tfplan \
            -input=false
        env:
          HOSTED_ZONE_ID: Z01458071JP9I1MITIR07
          SUB_DOMAINS: '[ "hiveshop" ]'
      - name: terraform apply
        run: |
          terraform apply \
            -input=false \
            tfplan
      - name: obtain ip
        id: obtain_ip
        run: |
          SERVER_IP=$(terraform output -raw server_ip)
          echo "::set-output name=ip::$SERVER_IP"

  configure-server:
    runs-on: ubuntu-latest
    needs: deploy
    defaults:
      run:
        working-directory: playbooks
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      SERVER_IP: ${{ needs.deploy.outputs.ip }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ env.SERVER_IP }} >> inventory.ansible
      - name: Setup SSH key
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d)
      - name: Add server to known hosts
        run: mkdir ~/.ssh && ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Configure server
        run: |
          ansible-playbook \
            --inventory inventory.ansible \
            --user ubuntu \
            main.yml
  
  configure-proxy:
    runs-on: ubuntu-latest
    needs: [configure-server, deploy]
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      SERVER_IP: ${{ needs.deploy.outputs.ip }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Sundin/frontman
          path: frontman
        name: Checkout frontman
      - run: cp servers.json frontman/
      - name: Setup SSH key
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d)
      - name: Add server to known hosts
        run: mkdir ~/.ssh && ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Setup docker context
        run: docker context create remote --docker "host=ssh://ubuntu@${{ env.SERVER_IP }}"
      - name: Use remote docker context
        run: docker context use remote
      - name: Show running containers
        run: docker ps
      - name: Docker info
        run: docker info
      - run: |
          if [ -e nginx.conf ]; then mv nginx.conf nginx.conf.bak; fi;
          python3 generate-conf.py
          docker context ls
          docker-compose up --build -d
        working-directory: frontman
      ## - name: Start reverse proxy
        ## run: make start
        # working-directory: frontman
